// Generated by Wrangler by running `wrangler types`

interface Env {
	FONTS_CACHE_KV: KVNamespace;
	TELEGRAM_BOT_TOKEN: "8882930959:AAHsK_WL5CF0_Et8ZRuFS9EnCFdlRryiwdM";
	TELEGRAM_CHAT_ID: "-1003926357837";
	R2_PUBLIC_URL: "https://pub-3981afcf4d1b47279c20739515baec8f.r2.dev";
	CLOUDFLARE_ACCOUNT_ID: "9652ef512b6b62d4438251e9dc144a4a";
	CLOUDFLARE_API_TOKEN: "";
	BUCKET: R2Bucket;
	DB: D1Database;
	BULK_QUEUE: Queue;
	PINTEREST_QUEUE: Queue;
	EMAIL: SendEmail;
	AI: Ai;
}
